// <auto-generated />
using System;
using ClinicksApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicksApi.Migrations
{
    [DbContext(typeof(ClinicksDbContext))]
    partial class ClinicksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicksApi.Data.Entities.Cama", b =>
                {
                    b.Property<int>("IdCama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cama");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCama"));

                    b.Property<string>("CodigoCama")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_cama");

                    b.Property<int>("IdEstadoCama")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_cama");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_habitacion");

                    b.HasKey("IdCama")
                        .HasName("cama_pkey");

                    b.HasIndex("IdEstadoCama");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex(new[] { "CodigoCama" }, "cama_codigo_cama_key")
                        .IsUnique();

                    b.ToTable("cama", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ciudad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCiudad"));

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCiudad")
                        .HasName("ciudad_pkey");

                    b.HasIndex("IdPais");

                    b.ToTable("ciudad", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.CodigoPostal", b =>
                {
                    b.Property<int>("IdCodigoPostal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_codigo_postal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodigoPostal"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("integer")
                        .HasColumnName("id_ciudad");

                    b.HasKey("IdCodigoPostal")
                        .HasName("codigo_postal_pkey");

                    b.HasIndex("IdCiudad");

                    b.HasIndex(new[] { "Codigo" }, "codigo_postal_codigo_key")
                        .IsUnique();

                    b.ToTable("codigo_postal", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.ConsultaMedica", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<DateTime?>("FechaConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_consulta")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdMedico")
                        .HasColumnType("integer")
                        .HasColumnName("id_medico");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<string>("Recomendacion")
                        .HasColumnType("text")
                        .HasColumnName("recomendacion");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("text")
                        .HasColumnName("tratamiento");

                    b.HasKey("IdConsulta")
                        .HasName("consulta_medica_pkey");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("consulta_medica", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_direccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDireccion"));

                    b.Property<int>("IdCodigoPostal")
                        .HasColumnType("integer")
                        .HasColumnName("id_codigo_postal");

                    b.Property<string>("NombreCalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_calle");

                    b.Property<int?>("NumeroCalle")
                        .HasColumnType("integer")
                        .HasColumnName("numero_calle");

                    b.HasKey("IdDireccion")
                        .HasName("direccion_pkey");

                    b.HasIndex("IdCodigoPostal");

                    b.ToTable("direccion", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEspecialidad")
                        .HasName("especialidad_pkey");

                    b.HasIndex(new[] { "Nombre" }, "especialidad_nombre_key")
                        .IsUnique();

                    b.ToTable("especialidad", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoCama", b =>
                {
                    b.Property<int>("IdEstadoCama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_cama");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoCama"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoCama")
                        .HasName("estado_cama_pkey");

                    b.HasIndex(new[] { "Nombre" }, "estado_cama_nombre_key")
                        .IsUnique();

                    b.ToTable("estado_cama", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoPaciente", b =>
                {
                    b.Property<int>("IdEstadoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoPaciente"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoPaciente")
                        .HasName("estado_paciente_pkey");

                    b.HasIndex(new[] { "Nombre" }, "estado_paciente_nombre_key")
                        .IsUnique();

                    b.ToTable("estado_paciente", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoTurno", b =>
                {
                    b.Property<int>("IdEstadoTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_turno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoTurno"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoTurno")
                        .HasName("estado_turno_pkey");

                    b.HasIndex(new[] { "Nombre" }, "estado_turno_nombre_key")
                        .IsUnique();

                    b.ToTable("estado_turno", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoUsuario", b =>
                {
                    b.Property<int>("IdEstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoUsuario"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoUsuario")
                        .HasName("estado_usuario_pkey");

                    b.HasIndex(new[] { "Nombre" }, "estado_usuario_nombre_key")
                        .IsUnique();

                    b.ToTable("estado_usuario", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_habitacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHabitacion"));

                    b.Property<int>("IdPiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_piso");

                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_habitacion");

                    b.Property<int>("NroHabitacion")
                        .HasColumnType("integer")
                        .HasColumnName("nro_habitacion");

                    b.HasKey("IdHabitacion")
                        .HasName("habitacion_pkey");

                    b.HasIndex("IdPiso");

                    b.HasIndex("IdTipoHabitacion");

                    b.HasIndex(new[] { "NroHabitacion", "IdPiso" }, "habitacion_nro_habitacion_id_piso_key")
                        .IsUnique();

                    b.ToTable("habitacion", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Internacion", b =>
                {
                    b.Property<int>("IdInternacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_internacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInternacion"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdCama")
                        .HasColumnType("integer")
                        .HasColumnName("id_cama");

                    b.Property<int>("IdMedico")
                        .HasColumnType("integer")
                        .HasColumnName("id_medico");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("IdInternacion")
                        .HasName("internacion_pkey");

                    b.HasIndex("IdCama");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("internacion", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Medicacion", b =>
                {
                    b.Property<int>("IdMedicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_medicacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedicacion"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dosis");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frecuencia");

                    b.Property<int>("IdInternacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_internacion");

                    b.Property<string>("NombreMedicamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_medicamento");

                    b.HasKey("IdMedicacion")
                        .HasName("medicacion_pkey");

                    b.HasIndex("IdInternacion");

                    b.ToTable("medicacion", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_medico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedico"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("dni");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_direccion");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMedico")
                        .HasName("medico_pkey");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex(new[] { "Correo" }, "medico_correo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Dni" }, "medico_dni_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Matricula" }, "medico_matricula_key")
                        .IsUnique();

                    b.ToTable("medico", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("dni");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("FechaRegistracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registracion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_direccion");

                    b.Property<int>("IdEstadoPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_paciente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("IdPaciente")
                        .HasName("paciente_pkey");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstadoPaciente");

                    b.HasIndex(new[] { "Correo" }, "paciente_correo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Dni" }, "paciente_dni_key")
                        .IsUnique();

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPais")
                        .HasName("pais_pkey");

                    b.HasIndex(new[] { "Nombre" }, "pais_nombre_key")
                        .IsUnique();

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Piso", b =>
                {
                    b.Property<int>("IdPiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_piso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPiso"));

                    b.Property<string>("NroPiso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nro_piso");

                    b.HasKey("IdPiso")
                        .HasName("piso_pkey");

                    b.HasIndex(new[] { "NroPiso" }, "piso_nro_piso_key")
                        .IsUnique();

                    b.ToTable("piso", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Procedimiento", b =>
                {
                    b.Property<int>("IdProcedimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_procedimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProcedimiento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Resultado")
                        .HasColumnType("text")
                        .HasColumnName("resultado");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("IdProcedimiento")
                        .HasName("procedimiento_pkey");

                    b.ToTable("procedimiento", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("rol_pkey");

                    b.HasIndex(new[] { "Nombre" }, "rol_nombre_key")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Telefono", b =>
                {
                    b.Property<int>("IdTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_telefono");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTelefono"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_telefono");

                    b.HasKey("IdTelefono")
                        .HasName("telefono_pkey");

                    b.HasIndex("IdPaciente");

                    b.ToTable("telefono", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.TipoHabitacion", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_habitacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoHabitacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("tipo_habitacion_pkey");

                    b.HasIndex(new[] { "Nombre" }, "tipo_habitacion_nombre_key")
                        .IsUnique();

                    b.ToTable("tipo_habitacion", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_turno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<DateTime?>("FechaRegistracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registracion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaTurno")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_turno");

                    b.Property<int?>("IdConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<int>("IdEstadoTurno")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_turno");

                    b.Property<int>("IdMedico")
                        .HasColumnType("integer")
                        .HasColumnName("id_medico");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<int?>("IdProcedimiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_procedimiento");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdTurno")
                        .HasName("turno_pkey");

                    b.HasIndex("IdConsulta");

                    b.HasIndex("IdEstadoTurno");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdProcedimiento");

                    b.ToTable("turno", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<int>("IdEstadoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_pkey");

                    b.HasIndex("IdEstadoUsuario");

                    b.HasIndex(new[] { "Correo" }, "usuario_correo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "usuario_username_key")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("usuario_rol_pkey");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Cama", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.EstadoCama", "IdEstadoCamaNavigation")
                        .WithMany("Camas")
                        .HasForeignKey("IdEstadoCama")
                        .IsRequired()
                        .HasConstraintName("cama_id_estado_cama_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Habitacion", "IdHabitacionNavigation")
                        .WithMany("Camas")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("cama_id_habitacion_fkey");

                    b.Navigation("IdEstadoCamaNavigation");

                    b.Navigation("IdHabitacionNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Ciudad", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Pais", "IdPaisNavigation")
                        .WithMany("Ciudads")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("ciudad_id_pais_fkey");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.CodigoPostal", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Ciudad", "IdCiudadNavigation")
                        .WithMany("CodigoPostals")
                        .HasForeignKey("IdCiudad")
                        .IsRequired()
                        .HasConstraintName("codigo_postal_id_ciudad_fkey");

                    b.Navigation("IdCiudadNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.ConsultaMedica", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Medico", "IdMedicoNavigation")
                        .WithMany("ConsultaMedicas")
                        .HasForeignKey("IdMedico")
                        .IsRequired()
                        .HasConstraintName("consulta_medica_id_medico_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Paciente", "IdPacienteNavigation")
                        .WithMany("ConsultaMedicas")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("consulta_medica_id_paciente_fkey");

                    b.Navigation("IdMedicoNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Direccion", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.CodigoPostal", "IdCodigoPostalNavigation")
                        .WithMany("Direccions")
                        .HasForeignKey("IdCodigoPostal")
                        .IsRequired()
                        .HasConstraintName("direccion_id_codigo_postal_fkey");

                    b.Navigation("IdCodigoPostalNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Habitacion", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Piso", "IdPisoNavigation")
                        .WithMany("Habitacions")
                        .HasForeignKey("IdPiso")
                        .IsRequired()
                        .HasConstraintName("habitacion_id_piso_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.TipoHabitacion", "IdTipoHabitacionNavigation")
                        .WithMany("Habitacions")
                        .HasForeignKey("IdTipoHabitacion")
                        .IsRequired()
                        .HasConstraintName("habitacion_id_tipo_habitacion_fkey");

                    b.Navigation("IdPisoNavigation");

                    b.Navigation("IdTipoHabitacionNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Internacion", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Cama", "IdCamaNavigation")
                        .WithMany("Internacions")
                        .HasForeignKey("IdCama")
                        .IsRequired()
                        .HasConstraintName("internacion_id_cama_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Medico", "IdMedicoNavigation")
                        .WithMany("Internacions")
                        .HasForeignKey("IdMedico")
                        .IsRequired()
                        .HasConstraintName("internacion_id_medico_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Paciente", "IdPacienteNavigation")
                        .WithMany("Internacions")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("internacion_id_paciente_fkey");

                    b.Navigation("IdCamaNavigation");

                    b.Navigation("IdMedicoNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Medicacion", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Internacion", "IdInternacionNavigation")
                        .WithMany("Medicacions")
                        .HasForeignKey("IdInternacion")
                        .IsRequired()
                        .HasConstraintName("medicacion_id_internacion_fkey");

                    b.Navigation("IdInternacionNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Medico", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Direccion", "IdDireccionNavigation")
                        .WithMany("Medicos")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("medico_id_direccion_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Especialidad", "IdEspecialidadNavigation")
                        .WithMany("Medicos")
                        .HasForeignKey("IdEspecialidad")
                        .IsRequired()
                        .HasConstraintName("medico_id_especialidad_fkey");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("IdEspecialidadNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Paciente", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Direccion", "IdDireccionNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("paciente_id_direccion_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.EstadoPaciente", "IdEstadoPacienteNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdEstadoPaciente")
                        .IsRequired()
                        .HasConstraintName("paciente_id_estado_paciente_fkey");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("IdEstadoPacienteNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Telefono", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Paciente", "IdPacienteNavigation")
                        .WithMany("Telefonos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("telefono_id_paciente_fkey");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Turno", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.ConsultaMedica", "IdConsultaNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdConsulta")
                        .HasConstraintName("turno_id_consulta_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.EstadoTurno", "IdEstadoTurnoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdEstadoTurno")
                        .IsRequired()
                        .HasConstraintName("turno_id_estado_turno_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Medico", "IdMedicoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdMedico")
                        .IsRequired()
                        .HasConstraintName("turno_id_medico_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Paciente", "IdPacienteNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("turno_id_paciente_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Procedimiento", "IdProcedimientoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdProcedimiento")
                        .HasConstraintName("turno_id_procedimiento_fkey");

                    b.Navigation("IdConsultaNavigation");

                    b.Navigation("IdEstadoTurnoNavigation");

                    b.Navigation("IdMedicoNavigation");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProcedimientoNavigation");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Usuario", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.EstadoUsuario", "IdEstadoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstadoUsuario")
                        .IsRequired()
                        .HasConstraintName("usuario_id_estado_usuario_fkey");

                    b.Navigation("IdEstadoUsuarioNavigation");
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.HasOne("ClinicksApi.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("usuario_rol_id_rol_fkey");

                    b.HasOne("ClinicksApi.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("usuario_rol_id_usuario_fkey");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Cama", b =>
                {
                    b.Navigation("Internacions");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Ciudad", b =>
                {
                    b.Navigation("CodigoPostals");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.CodigoPostal", b =>
                {
                    b.Navigation("Direccions");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.ConsultaMedica", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Direccion", b =>
                {
                    b.Navigation("Medicos");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoCama", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoPaciente", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Habitacion", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Internacion", b =>
                {
                    b.Navigation("Medicacions");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Medico", b =>
                {
                    b.Navigation("ConsultaMedicas");

                    b.Navigation("Internacions");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Paciente", b =>
                {
                    b.Navigation("ConsultaMedicas");

                    b.Navigation("Internacions");

                    b.Navigation("Telefonos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Pais", b =>
                {
                    b.Navigation("Ciudads");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Piso", b =>
                {
                    b.Navigation("Habitacions");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.Procedimiento", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicksApi.Data.Entities.TipoHabitacion", b =>
                {
                    b.Navigation("Habitacions");
                });
#pragma warning restore 612, 618
        }
    }
}
