CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE especialidad (
        id_especialidad integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        CONSTRAINT especialidad_pkey PRIMARY KEY (id_especialidad)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE estado_cama (
        id_estado_cama integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        CONSTRAINT estado_cama_pkey PRIMARY KEY (id_estado_cama)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE estado_paciente (
        id_estado_paciente integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        CONSTRAINT estado_paciente_pkey PRIMARY KEY (id_estado_paciente)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE estado_turno (
        id_estado_turno integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(30) NOT NULL,
        CONSTRAINT estado_turno_pkey PRIMARY KEY (id_estado_turno)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE estado_usuario (
        id_estado_usuario integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(30) NOT NULL,
        CONSTRAINT estado_usuario_pkey PRIMARY KEY (id_estado_usuario)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE pais (
        id_pais integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        CONSTRAINT pais_pkey PRIMARY KEY (id_pais)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE piso (
        id_piso integer GENERATED BY DEFAULT AS IDENTITY,
        nro_piso character varying(10) NOT NULL,
        CONSTRAINT piso_pkey PRIMARY KEY (id_piso)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE procedimiento (
        id_procedimiento integer GENERATED BY DEFAULT AS IDENTITY,
        tipo character varying(100) NOT NULL,
        descripcion text,
        fecha timestamp without time zone NOT NULL,
        resultado text,
        CONSTRAINT procedimiento_pkey PRIMARY KEY (id_procedimiento)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE rol (
        id_rol integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(30) NOT NULL,
        CONSTRAINT rol_pkey PRIMARY KEY (id_rol)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE tipo_habitacion (
        id_tipo_habitacion integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        CONSTRAINT tipo_habitacion_pkey PRIMARY KEY (id_tipo_habitacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE usuario (
        id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
        username character varying(50) NOT NULL,
        password character varying(255) NOT NULL,
        nombre character varying(50) NOT NULL,
        apellido character varying(50) NOT NULL,
        correo character varying(100),
        id_estado_usuario integer NOT NULL,
        CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
        CONSTRAINT usuario_id_estado_usuario_fkey FOREIGN KEY (id_estado_usuario) REFERENCES estado_usuario (id_estado_usuario)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE ciudad (
        id_ciudad integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        id_pais integer NOT NULL,
        CONSTRAINT ciudad_pkey PRIMARY KEY (id_ciudad),
        CONSTRAINT ciudad_id_pais_fkey FOREIGN KEY (id_pais) REFERENCES pais (id_pais)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE habitacion (
        id_habitacion integer GENERATED BY DEFAULT AS IDENTITY,
        nro_habitacion integer NOT NULL,
        id_piso integer NOT NULL,
        id_tipo_habitacion integer NOT NULL,
        CONSTRAINT habitacion_pkey PRIMARY KEY (id_habitacion),
        CONSTRAINT habitacion_id_piso_fkey FOREIGN KEY (id_piso) REFERENCES piso (id_piso),
        CONSTRAINT habitacion_id_tipo_habitacion_fkey FOREIGN KEY (id_tipo_habitacion) REFERENCES tipo_habitacion (id_tipo_habitacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE usuario_rol (
        id_usuario integer NOT NULL,
        id_rol integer NOT NULL,
        CONSTRAINT usuario_rol_pkey PRIMARY KEY (id_usuario, id_rol),
        CONSTRAINT usuario_rol_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES rol (id_rol),
        CONSTRAINT usuario_rol_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE codigo_postal (
        id_codigo_postal integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(15) NOT NULL,
        id_ciudad integer NOT NULL,
        CONSTRAINT codigo_postal_pkey PRIMARY KEY (id_codigo_postal),
        CONSTRAINT codigo_postal_id_ciudad_fkey FOREIGN KEY (id_ciudad) REFERENCES ciudad (id_ciudad)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE cama (
        id_cama integer GENERATED BY DEFAULT AS IDENTITY,
        codigo_cama character varying(30) NOT NULL,
        id_estado_cama integer NOT NULL,
        id_habitacion integer NOT NULL,
        CONSTRAINT cama_pkey PRIMARY KEY (id_cama),
        CONSTRAINT cama_id_estado_cama_fkey FOREIGN KEY (id_estado_cama) REFERENCES estado_cama (id_estado_cama),
        CONSTRAINT cama_id_habitacion_fkey FOREIGN KEY (id_habitacion) REFERENCES habitacion (id_habitacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE direccion (
        id_direccion integer GENERATED BY DEFAULT AS IDENTITY,
        nombre_calle character varying(100) NOT NULL,
        numero_calle integer,
        id_codigo_postal integer NOT NULL,
        CONSTRAINT direccion_pkey PRIMARY KEY (id_direccion),
        CONSTRAINT direccion_id_codigo_postal_fkey FOREIGN KEY (id_codigo_postal) REFERENCES codigo_postal (id_codigo_postal)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE medico (
        id_medico integer GENERATED BY DEFAULT AS IDENTITY,
        matricula character varying(30) NOT NULL,
        nombre character varying(50) NOT NULL,
        apellido character varying(50) NOT NULL,
        correo character varying(100),
        dni character varying(15) NOT NULL,
        id_especialidad integer NOT NULL,
        id_direccion integer NOT NULL,
        CONSTRAINT medico_pkey PRIMARY KEY (id_medico),
        CONSTRAINT medico_id_direccion_fkey FOREIGN KEY (id_direccion) REFERENCES direccion (id_direccion),
        CONSTRAINT medico_id_especialidad_fkey FOREIGN KEY (id_especialidad) REFERENCES especialidad (id_especialidad)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE paciente (
        id_paciente integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        apellido character varying(50) NOT NULL,
        fecha_nacimiento date NOT NULL,
        dni character varying(15) NOT NULL,
        correo character varying(100),
        observaciones text,
        fecha_registracion timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        id_estado_paciente integer NOT NULL,
        id_direccion integer NOT NULL,
        CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente),
        CONSTRAINT paciente_id_direccion_fkey FOREIGN KEY (id_direccion) REFERENCES direccion (id_direccion),
        CONSTRAINT paciente_id_estado_paciente_fkey FOREIGN KEY (id_estado_paciente) REFERENCES estado_paciente (id_estado_paciente)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE consulta_medica (
        id_consulta integer GENERATED BY DEFAULT AS IDENTITY,
        motivo text NOT NULL,
        diagnostico text NOT NULL,
        recomendacion text,
        fecha_consulta timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        observacion text,
        tratamiento text,
        id_paciente integer NOT NULL,
        id_medico integer NOT NULL,
        CONSTRAINT consulta_medica_pkey PRIMARY KEY (id_consulta),
        CONSTRAINT consulta_medica_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES medico (id_medico),
        CONSTRAINT consulta_medica_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE internacion (
        id_internacion integer GENERATED BY DEFAULT AS IDENTITY,
        fecha_inicio timestamp without time zone NOT NULL,
        fecha_fin timestamp without time zone,
        motivo text NOT NULL,
        id_paciente integer NOT NULL,
        id_medico integer NOT NULL,
        id_cama integer NOT NULL,
        CONSTRAINT internacion_pkey PRIMARY KEY (id_internacion),
        CONSTRAINT internacion_id_cama_fkey FOREIGN KEY (id_cama) REFERENCES cama (id_cama),
        CONSTRAINT internacion_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES medico (id_medico),
        CONSTRAINT internacion_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE telefono (
        id_telefono integer GENERATED BY DEFAULT AS IDENTITY,
        numero_telefono character varying(20) NOT NULL,
        id_paciente integer NOT NULL,
        CONSTRAINT telefono_pkey PRIMARY KEY (id_telefono),
        CONSTRAINT telefono_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE turno (
        id_turno integer GENERATED BY DEFAULT AS IDENTITY,
        fecha_turno timestamp without time zone NOT NULL,
        fecha_registracion timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        motivo character varying(200),
        id_paciente integer NOT NULL,
        id_medico integer NOT NULL,
        id_estado_turno integer NOT NULL,
        id_procedimiento integer,
        id_consulta integer,
        CONSTRAINT turno_pkey PRIMARY KEY (id_turno),
        CONSTRAINT turno_id_consulta_fkey FOREIGN KEY (id_consulta) REFERENCES consulta_medica (id_consulta),
        CONSTRAINT turno_id_estado_turno_fkey FOREIGN KEY (id_estado_turno) REFERENCES estado_turno (id_estado_turno),
        CONSTRAINT turno_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES medico (id_medico),
        CONSTRAINT turno_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente),
        CONSTRAINT turno_id_procedimiento_fkey FOREIGN KEY (id_procedimiento) REFERENCES procedimiento (id_procedimiento)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE TABLE medicacion (
        id_medicacion integer GENERATED BY DEFAULT AS IDENTITY,
        nombre_medicamento character varying(100) NOT NULL,
        dosis character varying(50) NOT NULL,
        frecuencia character varying(100) NOT NULL,
        fecha_inicio timestamp without time zone NOT NULL,
        fecha_fin timestamp without time zone,
        id_internacion integer NOT NULL,
        CONSTRAINT medicacion_pkey PRIMARY KEY (id_medicacion),
        CONSTRAINT medicacion_id_internacion_fkey FOREIGN KEY (id_internacion) REFERENCES internacion (id_internacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX cama_codigo_cama_key ON cama (codigo_cama);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_cama_id_estado_cama" ON cama (id_estado_cama);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_cama_id_habitacion" ON cama (id_habitacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_ciudad_id_pais" ON ciudad (id_pais);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX codigo_postal_codigo_key ON codigo_postal (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_codigo_postal_id_ciudad" ON codigo_postal (id_ciudad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_consulta_medica_id_medico" ON consulta_medica (id_medico);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_consulta_medica_id_paciente" ON consulta_medica (id_paciente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_direccion_id_codigo_postal" ON direccion (id_codigo_postal);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX especialidad_nombre_key ON especialidad (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX estado_cama_nombre_key ON estado_cama (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX estado_paciente_nombre_key ON estado_paciente (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX estado_turno_nombre_key ON estado_turno (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX estado_usuario_nombre_key ON estado_usuario (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX habitacion_nro_habitacion_id_piso_key ON habitacion (nro_habitacion, id_piso);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_habitacion_id_piso" ON habitacion (id_piso);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_habitacion_id_tipo_habitacion" ON habitacion (id_tipo_habitacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_internacion_id_cama" ON internacion (id_cama);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_internacion_id_medico" ON internacion (id_medico);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_internacion_id_paciente" ON internacion (id_paciente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_medicacion_id_internacion" ON medicacion (id_internacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_medico_id_direccion" ON medico (id_direccion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_medico_id_especialidad" ON medico (id_especialidad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX medico_correo_key ON medico (correo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX medico_dni_key ON medico (dni);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX medico_matricula_key ON medico (matricula);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_paciente_id_direccion" ON paciente (id_direccion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_paciente_id_estado_paciente" ON paciente (id_estado_paciente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX paciente_correo_key ON paciente (correo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX paciente_dni_key ON paciente (dni);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX pais_nombre_key ON pais (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX piso_nro_piso_key ON piso (nro_piso);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX rol_nombre_key ON rol (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_telefono_id_paciente" ON telefono (id_paciente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX tipo_habitacion_nombre_key ON tipo_habitacion (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_turno_id_consulta" ON turno (id_consulta);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_turno_id_estado_turno" ON turno (id_estado_turno);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_turno_id_medico" ON turno (id_medico);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_turno_id_paciente" ON turno (id_paciente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_turno_id_procedimiento" ON turno (id_procedimiento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_usuario_id_estado_usuario" ON usuario (id_estado_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX usuario_correo_key ON usuario (correo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE UNIQUE INDEX usuario_username_key ON usuario (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    CREATE INDEX "IX_usuario_rol_id_rol" ON usuario_rol (id_rol);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419151956_ReinstalacionInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419151956_ReinstalacionInicial', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511054135_UpdateSchema') THEN
    ALTER TABLE medico ADD id_usuario integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511054135_UpdateSchema') THEN
    CREATE INDEX "IX_medico_id_usuario" ON medico (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511054135_UpdateSchema') THEN
    ALTER TABLE medico ADD CONSTRAINT fk_medico_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511054135_UpdateSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511054135_UpdateSchema', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260608135547_AddStoredProcedures') THEN

                    CREATE OR REPLACE PROCEDURE ActualizarEstadoTurnoSP(
                        p_idTurno INT,
                        p_idEstado INT,
                        p_idConsulta INT DEFAULT NULL,
                        p_idProcedimiento INT DEFAULT NULL
                    )
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        UPDATE "turno"
                        SET "id_estado_turno" = p_idEstado,
                            "id_consulta" = COALESCE(p_idConsulta, "id_consulta"),
                            "id_procedimiento" = COALESCE(p_idProcedimiento, "id_procedimiento")
                        WHERE "id_turno" = p_idTurno;
                    END;
                    $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260608135547_AddStoredProcedures') THEN

                    CREATE OR REPLACE FUNCTION ObtenerTurnosPorMedico(p_idMedico INT)
                    RETURNS SETOF "turno"
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        RETURN QUERY
                        SELECT *
                        FROM "turno"
                        WHERE "id_medico" = p_idMedico;
                    END;
                    $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260608135547_AddStoredProcedures') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260608135547_AddStoredProcedures', '8.0.27');
    END IF;
END $EF$;
COMMIT;

